# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  push:
    branches:
      - master
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Get git commit info
        id: commit
        run: |
          echo "GIT_HASH=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
          echo "GIT_DATE=$(git log -1 --format=%cd --date=short)" >> $GITHUB_ENV

      - name: Inject git info into index.html
        run: |
          FILE="webtx/index.html"
          INFO="Ver: ${{ env.GIT_HASH }}, Date: ${{ env.GIT_DATE }}"
          sed -i "s/%VER%/$INFO/g" "$FILE"

      - name: Upload static site
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'webtx'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
